import request from '@/utils/request'

export const getPublicConfig = () => request.get('/config')
export const listPackages = (params?: any) => request.get('/packages', { params })
export const getPackage = (id: number) => request.get(`/packages/${id}`)
export const listNotifications = (params?: any) => request.get('/notifications', { params })
export const getUnreadCount = () => request.get('/notifications/unread-count')
export const markNotificationRead = (id: number) => request.put(`/notifications/${id}/read`)
export const markAllRead = () => request.put('/notifications/read-all')
export const deleteNotification = (id: number) => request.delete(`/notifications/${id}`)
export const verifyCoupon = (data: { code: string; package_id: number }) =>
  request.post('/coupons/verify', data)
export const getMyCoupons = () => request.get('/coupons/my')
export const listInviteCodes = (params?: any) => request.get('/invites', { params })
export const createInviteCode = (data: any) => request.post('/invites', data)
export const getInviteStats = () => request.get('/invites/stats')
export const getMyCodes = () => request.get('/invites/my-codes')
export const validateInviteCode = (code: string) => request.get(`/invites/validate/${code}`)
export const redeemCode = (data: { code: string }) => request.post('/redeem', data)
export const getRedeemHistory = (params?: any) => request.get('/redeem/history', { params })
export const listDevices = () => request.get('/devices')
export const deleteDeviceById = (id: number) => request.delete(`/devices/${id}`)
export const listRechargeRecords = (params?: any) => request.get('/recharge', { params })
export const createRecharge = (data: any) => request.post('/recharge', data)
export const cancelRecharge = (id: number) => request.post(`/recharge/${id}/cancel`)
export const getPaymentMethods = () => request.get('/payment/methods')
export const listPublicAnnouncements = () => request.get('/announcements')
export const deleteInviteCode = (id: number) => request.delete(`/invites/${id}`)
